### ISSUE TITLE
Uploader Syntax Error

### ISSUE THREAD

**Issue by cyb3rgh05t** [dockserver/dockserver#280]
I get syntax error in uploader:

![image](https://user-images.githubusercontent.com/5200101/140660727-c4c8ebc9-30c4-4ef9-aa8c-e07dac449964.png)

**Comment by doob187** [comment]
Fixed

redeploy the container 

or 

wait until dockupdater  redeploy the container

**Comment by cyb3rgh05t** [comment]
Yes i did but i still have the syntax error. could it be somthing at my end?
